/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ActivityZone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActivityZoneTests
    {
        // TODO uncomment below to declare an instance variable for ActivityZone
        //private ActivityZone instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActivityZone
            //instance = new ActivityZone();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActivityZone
        /// </summary>
        [Test]
        public void ActivityZoneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ActivityZone
            //Assert.IsInstanceOfType<ActivityZone> (instance, "variable 'instance' is a ActivityZone");
        }


        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'DistributionBuckets'
        /// </summary>
        [Test]
        public void DistributionBucketsTest()
        {
            // TODO unit test for the property 'DistributionBuckets'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SensorBased'
        /// </summary>
        [Test]
        public void SensorBasedTest()
        {
            // TODO unit test for the property 'SensorBased'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
        /// <summary>
        /// Test the property 'CustomZones'
        /// </summary>
        [Test]
        public void CustomZonesTest()
        {
            // TODO unit test for the property 'CustomZones'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Test]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }

    }

}
