/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ActivityStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActivityStatsTests
    {
        // TODO uncomment below to declare an instance variable for ActivityStats
        //private ActivityStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActivityStats
            //instance = new ActivityStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActivityStats
        /// </summary>
        [Test]
        public void ActivityStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ActivityStats
            //Assert.IsInstanceOfType<ActivityStats> (instance, "variable 'instance' is a ActivityStats");
        }


        /// <summary>
        /// Test the property 'BiggestRideDistance'
        /// </summary>
        [Test]
        public void BiggestRideDistanceTest()
        {
            // TODO unit test for the property 'BiggestRideDistance'
        }
        /// <summary>
        /// Test the property 'BiggestClimbElevationGain'
        /// </summary>
        [Test]
        public void BiggestClimbElevationGainTest()
        {
            // TODO unit test for the property 'BiggestClimbElevationGain'
        }
        /// <summary>
        /// Test the property 'RecentRideTotals'
        /// </summary>
        [Test]
        public void RecentRideTotalsTest()
        {
            // TODO unit test for the property 'RecentRideTotals'
        }
        /// <summary>
        /// Test the property 'RecentRunTotals'
        /// </summary>
        [Test]
        public void RecentRunTotalsTest()
        {
            // TODO unit test for the property 'RecentRunTotals'
        }
        /// <summary>
        /// Test the property 'RecentSwimTotals'
        /// </summary>
        [Test]
        public void RecentSwimTotalsTest()
        {
            // TODO unit test for the property 'RecentSwimTotals'
        }
        /// <summary>
        /// Test the property 'YtdRideTotals'
        /// </summary>
        [Test]
        public void YtdRideTotalsTest()
        {
            // TODO unit test for the property 'YtdRideTotals'
        }
        /// <summary>
        /// Test the property 'YtdRunTotals'
        /// </summary>
        [Test]
        public void YtdRunTotalsTest()
        {
            // TODO unit test for the property 'YtdRunTotals'
        }
        /// <summary>
        /// Test the property 'YtdSwimTotals'
        /// </summary>
        [Test]
        public void YtdSwimTotalsTest()
        {
            // TODO unit test for the property 'YtdSwimTotals'
        }
        /// <summary>
        /// Test the property 'AllRideTotals'
        /// </summary>
        [Test]
        public void AllRideTotalsTest()
        {
            // TODO unit test for the property 'AllRideTotals'
        }
        /// <summary>
        /// Test the property 'AllRunTotals'
        /// </summary>
        [Test]
        public void AllRunTotalsTest()
        {
            // TODO unit test for the property 'AllRunTotals'
        }
        /// <summary>
        /// Test the property 'AllSwimTotals'
        /// </summary>
        [Test]
        public void AllSwimTotalsTest()
        {
            // TODO unit test for the property 'AllSwimTotals'
        }

    }

}
