/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ActivityTotal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActivityTotalTests
    {
        // TODO uncomment below to declare an instance variable for ActivityTotal
        //private ActivityTotal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActivityTotal
            //instance = new ActivityTotal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActivityTotal
        /// </summary>
        [Test]
        public void ActivityTotalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ActivityTotal
            //Assert.IsInstanceOfType<ActivityTotal> (instance, "variable 'instance' is a ActivityTotal");
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'MovingTime'
        /// </summary>
        [Test]
        public void MovingTimeTest()
        {
            // TODO unit test for the property 'MovingTime'
        }
        /// <summary>
        /// Test the property 'ElapsedTime'
        /// </summary>
        [Test]
        public void ElapsedTimeTest()
        {
            // TODO unit test for the property 'ElapsedTime'
        }
        /// <summary>
        /// Test the property 'ElevationGain'
        /// </summary>
        [Test]
        public void ElevationGainTest()
        {
            // TODO unit test for the property 'ElevationGain'
        }
        /// <summary>
        /// Test the property 'AchievementCount'
        /// </summary>
        [Test]
        public void AchievementCountTest()
        {
            // TODO unit test for the property 'AchievementCount'
        }

    }

}
