/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DetailedAthlete
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetailedAthleteTests
    {
        // TODO uncomment below to declare an instance variable for DetailedAthlete
        //private DetailedAthlete instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetailedAthlete
            //instance = new DetailedAthlete();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetailedAthlete
        /// </summary>
        [Test]
        public void DetailedAthleteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetailedAthlete
            //Assert.IsInstanceOfType<DetailedAthlete> (instance, "variable 'instance' is a DetailedAthlete");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ResourceState'
        /// </summary>
        [Test]
        public void ResourceStateTest()
        {
            // TODO unit test for the property 'ResourceState'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'ProfileMedium'
        /// </summary>
        [Test]
        public void ProfileMediumTest()
        {
            // TODO unit test for the property 'ProfileMedium'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Sex'
        /// </summary>
        [Test]
        public void SexTest()
        {
            // TODO unit test for the property 'Sex'
        }
        /// <summary>
        /// Test the property 'Friend'
        /// </summary>
        [Test]
        public void FriendTest()
        {
            // TODO unit test for the property 'Friend'
        }
        /// <summary>
        /// Test the property 'Follower'
        /// </summary>
        [Test]
        public void FollowerTest()
        {
            // TODO unit test for the property 'Follower'
        }
        /// <summary>
        /// Test the property 'Premium'
        /// </summary>
        [Test]
        public void PremiumTest()
        {
            // TODO unit test for the property 'Premium'
        }
        /// <summary>
        /// Test the property 'Summit'
        /// </summary>
        [Test]
        public void SummitTest()
        {
            // TODO unit test for the property 'Summit'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'FollowerCount'
        /// </summary>
        [Test]
        public void FollowerCountTest()
        {
            // TODO unit test for the property 'FollowerCount'
        }
        /// <summary>
        /// Test the property 'FriendCount'
        /// </summary>
        [Test]
        public void FriendCountTest()
        {
            // TODO unit test for the property 'FriendCount'
        }
        /// <summary>
        /// Test the property 'MutualFriendCount'
        /// </summary>
        [Test]
        public void MutualFriendCountTest()
        {
            // TODO unit test for the property 'MutualFriendCount'
        }
        /// <summary>
        /// Test the property 'MeasurementPreference'
        /// </summary>
        [Test]
        public void MeasurementPreferenceTest()
        {
            // TODO unit test for the property 'MeasurementPreference'
        }
        /// <summary>
        /// Test the property 'Ftp'
        /// </summary>
        [Test]
        public void FtpTest()
        {
            // TODO unit test for the property 'Ftp'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Clubs'
        /// </summary>
        [Test]
        public void ClubsTest()
        {
            // TODO unit test for the property 'Clubs'
        }
        /// <summary>
        /// Test the property 'Bikes'
        /// </summary>
        [Test]
        public void BikesTest()
        {
            // TODO unit test for the property 'Bikes'
        }
        /// <summary>
        /// Test the property 'Shoes'
        /// </summary>
        [Test]
        public void ShoesTest()
        {
            // TODO unit test for the property 'Shoes'
        }

    }

}
