/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DetailedActivity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetailedActivityTests
    {
        // TODO uncomment below to declare an instance variable for DetailedActivity
        //private DetailedActivity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetailedActivity
            //instance = new DetailedActivity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetailedActivity
        /// </summary>
        [Test]
        public void DetailedActivityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetailedActivity
            //Assert.IsInstanceOfType<DetailedActivity> (instance, "variable 'instance' is a DetailedActivity");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'UploadId'
        /// </summary>
        [Test]
        public void UploadIdTest()
        {
            // TODO unit test for the property 'UploadId'
        }
        /// <summary>
        /// Test the property 'Athlete'
        /// </summary>
        [Test]
        public void AthleteTest()
        {
            // TODO unit test for the property 'Athlete'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'MovingTime'
        /// </summary>
        [Test]
        public void MovingTimeTest()
        {
            // TODO unit test for the property 'MovingTime'
        }
        /// <summary>
        /// Test the property 'ElapsedTime'
        /// </summary>
        [Test]
        public void ElapsedTimeTest()
        {
            // TODO unit test for the property 'ElapsedTime'
        }
        /// <summary>
        /// Test the property 'TotalElevationGain'
        /// </summary>
        [Test]
        public void TotalElevationGainTest()
        {
            // TODO unit test for the property 'TotalElevationGain'
        }
        /// <summary>
        /// Test the property 'ElevHigh'
        /// </summary>
        [Test]
        public void ElevHighTest()
        {
            // TODO unit test for the property 'ElevHigh'
        }
        /// <summary>
        /// Test the property 'ElevLow'
        /// </summary>
        [Test]
        public void ElevLowTest()
        {
            // TODO unit test for the property 'ElevLow'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'StartDateLocal'
        /// </summary>
        [Test]
        public void StartDateLocalTest()
        {
            // TODO unit test for the property 'StartDateLocal'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
        /// <summary>
        /// Test the property 'StartLatlng'
        /// </summary>
        [Test]
        public void StartLatlngTest()
        {
            // TODO unit test for the property 'StartLatlng'
        }
        /// <summary>
        /// Test the property 'EndLatlng'
        /// </summary>
        [Test]
        public void EndLatlngTest()
        {
            // TODO unit test for the property 'EndLatlng'
        }
        /// <summary>
        /// Test the property 'AchievementCount'
        /// </summary>
        [Test]
        public void AchievementCountTest()
        {
            // TODO unit test for the property 'AchievementCount'
        }
        /// <summary>
        /// Test the property 'KudosCount'
        /// </summary>
        [Test]
        public void KudosCountTest()
        {
            // TODO unit test for the property 'KudosCount'
        }
        /// <summary>
        /// Test the property 'CommentCount'
        /// </summary>
        [Test]
        public void CommentCountTest()
        {
            // TODO unit test for the property 'CommentCount'
        }
        /// <summary>
        /// Test the property 'AthleteCount'
        /// </summary>
        [Test]
        public void AthleteCountTest()
        {
            // TODO unit test for the property 'AthleteCount'
        }
        /// <summary>
        /// Test the property 'PhotoCount'
        /// </summary>
        [Test]
        public void PhotoCountTest()
        {
            // TODO unit test for the property 'PhotoCount'
        }
        /// <summary>
        /// Test the property 'TotalPhotoCount'
        /// </summary>
        [Test]
        public void TotalPhotoCountTest()
        {
            // TODO unit test for the property 'TotalPhotoCount'
        }
        /// <summary>
        /// Test the property 'Map'
        /// </summary>
        [Test]
        public void MapTest()
        {
            // TODO unit test for the property 'Map'
        }
        /// <summary>
        /// Test the property 'Trainer'
        /// </summary>
        [Test]
        public void TrainerTest()
        {
            // TODO unit test for the property 'Trainer'
        }
        /// <summary>
        /// Test the property 'Commute'
        /// </summary>
        [Test]
        public void CommuteTest()
        {
            // TODO unit test for the property 'Commute'
        }
        /// <summary>
        /// Test the property 'Manual'
        /// </summary>
        [Test]
        public void ManualTest()
        {
            // TODO unit test for the property 'Manual'
        }
        /// <summary>
        /// Test the property 'Private'
        /// </summary>
        [Test]
        public void PrivateTest()
        {
            // TODO unit test for the property 'Private'
        }
        /// <summary>
        /// Test the property 'Flagged'
        /// </summary>
        [Test]
        public void FlaggedTest()
        {
            // TODO unit test for the property 'Flagged'
        }
        /// <summary>
        /// Test the property 'WorkoutType'
        /// </summary>
        [Test]
        public void WorkoutTypeTest()
        {
            // TODO unit test for the property 'WorkoutType'
        }
        /// <summary>
        /// Test the property 'AverageSpeed'
        /// </summary>
        [Test]
        public void AverageSpeedTest()
        {
            // TODO unit test for the property 'AverageSpeed'
        }
        /// <summary>
        /// Test the property 'MaxSpeed'
        /// </summary>
        [Test]
        public void MaxSpeedTest()
        {
            // TODO unit test for the property 'MaxSpeed'
        }
        /// <summary>
        /// Test the property 'HasKudoed'
        /// </summary>
        [Test]
        public void HasKudoedTest()
        {
            // TODO unit test for the property 'HasKudoed'
        }
        /// <summary>
        /// Test the property 'GearId'
        /// </summary>
        [Test]
        public void GearIdTest()
        {
            // TODO unit test for the property 'GearId'
        }
        /// <summary>
        /// Test the property 'Kilojoules'
        /// </summary>
        [Test]
        public void KilojoulesTest()
        {
            // TODO unit test for the property 'Kilojoules'
        }
        /// <summary>
        /// Test the property 'AverageWatts'
        /// </summary>
        [Test]
        public void AverageWattsTest()
        {
            // TODO unit test for the property 'AverageWatts'
        }
        /// <summary>
        /// Test the property 'DeviceWatts'
        /// </summary>
        [Test]
        public void DeviceWattsTest()
        {
            // TODO unit test for the property 'DeviceWatts'
        }
        /// <summary>
        /// Test the property 'MaxWatts'
        /// </summary>
        [Test]
        public void MaxWattsTest()
        {
            // TODO unit test for the property 'MaxWatts'
        }
        /// <summary>
        /// Test the property 'WeightedAverageWatts'
        /// </summary>
        [Test]
        public void WeightedAverageWattsTest()
        {
            // TODO unit test for the property 'WeightedAverageWatts'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Photos'
        /// </summary>
        [Test]
        public void PhotosTest()
        {
            // TODO unit test for the property 'Photos'
        }
        /// <summary>
        /// Test the property 'Gear'
        /// </summary>
        [Test]
        public void GearTest()
        {
            // TODO unit test for the property 'Gear'
        }
        /// <summary>
        /// Test the property 'Calories'
        /// </summary>
        [Test]
        public void CaloriesTest()
        {
            // TODO unit test for the property 'Calories'
        }
        /// <summary>
        /// Test the property 'SegmentEfforts'
        /// </summary>
        [Test]
        public void SegmentEffortsTest()
        {
            // TODO unit test for the property 'SegmentEfforts'
        }
        /// <summary>
        /// Test the property 'DeviceName'
        /// </summary>
        [Test]
        public void DeviceNameTest()
        {
            // TODO unit test for the property 'DeviceName'
        }
        /// <summary>
        /// Test the property 'EmbedToken'
        /// </summary>
        [Test]
        public void EmbedTokenTest()
        {
            // TODO unit test for the property 'EmbedToken'
        }
        /// <summary>
        /// Test the property 'SplitsMetric'
        /// </summary>
        [Test]
        public void SplitsMetricTest()
        {
            // TODO unit test for the property 'SplitsMetric'
        }
        /// <summary>
        /// Test the property 'SplitsStandard'
        /// </summary>
        [Test]
        public void SplitsStandardTest()
        {
            // TODO unit test for the property 'SplitsStandard'
        }
        /// <summary>
        /// Test the property 'Laps'
        /// </summary>
        [Test]
        public void LapsTest()
        {
            // TODO unit test for the property 'Laps'
        }
        /// <summary>
        /// Test the property 'BestEfforts'
        /// </summary>
        [Test]
        public void BestEffortsTest()
        {
            // TODO unit test for the property 'BestEfforts'
        }

    }

}
