/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExplorerSegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExplorerSegmentTests
    {
        // TODO uncomment below to declare an instance variable for ExplorerSegment
        //private ExplorerSegment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExplorerSegment
            //instance = new ExplorerSegment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExplorerSegment
        /// </summary>
        [Test]
        public void ExplorerSegmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExplorerSegment
            //Assert.IsInstanceOfType<ExplorerSegment> (instance, "variable 'instance' is a ExplorerSegment");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ClimbCategory'
        /// </summary>
        [Test]
        public void ClimbCategoryTest()
        {
            // TODO unit test for the property 'ClimbCategory'
        }
        /// <summary>
        /// Test the property 'ClimbCategoryDesc'
        /// </summary>
        [Test]
        public void ClimbCategoryDescTest()
        {
            // TODO unit test for the property 'ClimbCategoryDesc'
        }
        /// <summary>
        /// Test the property 'AvgGrade'
        /// </summary>
        [Test]
        public void AvgGradeTest()
        {
            // TODO unit test for the property 'AvgGrade'
        }
        /// <summary>
        /// Test the property 'StartLatlng'
        /// </summary>
        [Test]
        public void StartLatlngTest()
        {
            // TODO unit test for the property 'StartLatlng'
        }
        /// <summary>
        /// Test the property 'EndLatlng'
        /// </summary>
        [Test]
        public void EndLatlngTest()
        {
            // TODO unit test for the property 'EndLatlng'
        }
        /// <summary>
        /// Test the property 'ElevDifference'
        /// </summary>
        [Test]
        public void ElevDifferenceTest()
        {
            // TODO unit test for the property 'ElevDifference'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }

    }

}
