/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExplorerResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExplorerResponseTests
    {
        // TODO uncomment below to declare an instance variable for ExplorerResponse
        //private ExplorerResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExplorerResponse
            //instance = new ExplorerResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExplorerResponse
        /// </summary>
        [Test]
        public void ExplorerResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExplorerResponse
            //Assert.IsInstanceOfType<ExplorerResponse> (instance, "variable 'instance' is a ExplorerResponse");
        }


        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Test]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }

    }

}
