/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HeartRateZoneRanges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HeartRateZoneRangesTests
    {
        // TODO uncomment below to declare an instance variable for HeartRateZoneRanges
        //private HeartRateZoneRanges instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HeartRateZoneRanges
            //instance = new HeartRateZoneRanges();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HeartRateZoneRanges
        /// </summary>
        [Test]
        public void HeartRateZoneRangesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HeartRateZoneRanges
            //Assert.IsInstanceOfType<HeartRateZoneRanges> (instance, "variable 'instance' is a HeartRateZoneRanges");
        }


        /// <summary>
        /// Test the property 'CustomZones'
        /// </summary>
        [Test]
        public void CustomZonesTest()
        {
            // TODO unit test for the property 'CustomZones'
        }
        /// <summary>
        /// Test the property 'Zones'
        /// </summary>
        [Test]
        public void ZonesTest()
        {
            // TODO unit test for the property 'Zones'
        }

    }

}
