/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Lap
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LapTests
    {
        // TODO uncomment below to declare an instance variable for Lap
        //private Lap instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Lap
            //instance = new Lap();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Lap
        /// </summary>
        [Test]
        public void LapInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Lap
            //Assert.IsInstanceOfType<Lap> (instance, "variable 'instance' is a Lap");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Activity'
        /// </summary>
        [Test]
        public void ActivityTest()
        {
            // TODO unit test for the property 'Activity'
        }
        /// <summary>
        /// Test the property 'Athlete'
        /// </summary>
        [Test]
        public void AthleteTest()
        {
            // TODO unit test for the property 'Athlete'
        }
        /// <summary>
        /// Test the property 'AverageCadence'
        /// </summary>
        [Test]
        public void AverageCadenceTest()
        {
            // TODO unit test for the property 'AverageCadence'
        }
        /// <summary>
        /// Test the property 'AverageSpeed'
        /// </summary>
        [Test]
        public void AverageSpeedTest()
        {
            // TODO unit test for the property 'AverageSpeed'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'ElapsedTime'
        /// </summary>
        [Test]
        public void ElapsedTimeTest()
        {
            // TODO unit test for the property 'ElapsedTime'
        }
        /// <summary>
        /// Test the property 'StartIndex'
        /// </summary>
        [Test]
        public void StartIndexTest()
        {
            // TODO unit test for the property 'StartIndex'
        }
        /// <summary>
        /// Test the property 'EndIndex'
        /// </summary>
        [Test]
        public void EndIndexTest()
        {
            // TODO unit test for the property 'EndIndex'
        }
        /// <summary>
        /// Test the property 'LapIndex'
        /// </summary>
        [Test]
        public void LapIndexTest()
        {
            // TODO unit test for the property 'LapIndex'
        }
        /// <summary>
        /// Test the property 'MaxSpeed'
        /// </summary>
        [Test]
        public void MaxSpeedTest()
        {
            // TODO unit test for the property 'MaxSpeed'
        }
        /// <summary>
        /// Test the property 'MovingTime'
        /// </summary>
        [Test]
        public void MovingTimeTest()
        {
            // TODO unit test for the property 'MovingTime'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PaceZone'
        /// </summary>
        [Test]
        public void PaceZoneTest()
        {
            // TODO unit test for the property 'PaceZone'
        }
        /// <summary>
        /// Test the property 'Split'
        /// </summary>
        [Test]
        public void SplitTest()
        {
            // TODO unit test for the property 'Split'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'StartDateLocal'
        /// </summary>
        [Test]
        public void StartDateLocalTest()
        {
            // TODO unit test for the property 'StartDateLocal'
        }
        /// <summary>
        /// Test the property 'TotalElevationGain'
        /// </summary>
        [Test]
        public void TotalElevationGainTest()
        {
            // TODO unit test for the property 'TotalElevationGain'
        }

    }

}
