/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PhotosSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PhotosSummaryTests
    {
        // TODO uncomment below to declare an instance variable for PhotosSummary
        //private PhotosSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PhotosSummary
            //instance = new PhotosSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PhotosSummary
        /// </summary>
        [Test]
        public void PhotosSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PhotosSummary
            //Assert.IsInstanceOfType<PhotosSummary> (instance, "variable 'instance' is a PhotosSummary");
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Primary'
        /// </summary>
        [Test]
        public void PrimaryTest()
        {
            // TODO unit test for the property 'Primary'
        }

    }

}
