/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Route
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RouteTests
    {
        // TODO uncomment below to declare an instance variable for Route
        //private Route instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Route
            //instance = new Route();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Route
        /// </summary>
        [Test]
        public void RouteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Route
            //Assert.IsInstanceOfType<Route> (instance, "variable 'instance' is a Route");
        }


        /// <summary>
        /// Test the property 'Athlete'
        /// </summary>
        [Test]
        public void AthleteTest()
        {
            // TODO unit test for the property 'Athlete'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'ElevationGain'
        /// </summary>
        [Test]
        public void ElevationGainTest()
        {
            // TODO unit test for the property 'ElevationGain'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Map'
        /// </summary>
        [Test]
        public void MapTest()
        {
            // TODO unit test for the property 'Map'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Private'
        /// </summary>
        [Test]
        public void PrivateTest()
        {
            // TODO unit test for the property 'Private'
        }
        /// <summary>
        /// Test the property 'Starred'
        /// </summary>
        [Test]
        public void StarredTest()
        {
            // TODO unit test for the property 'Starred'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SubType'
        /// </summary>
        [Test]
        public void SubTypeTest()
        {
            // TODO unit test for the property 'SubType'
        }
        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Test]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }
        /// <summary>
        /// Test the property 'Directions'
        /// </summary>
        [Test]
        public void DirectionsTest()
        {
            // TODO unit test for the property 'Directions'
        }

    }

}
