/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RunningRace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RunningRaceTests
    {
        // TODO uncomment below to declare an instance variable for RunningRace
        //private RunningRace instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RunningRace
            //instance = new RunningRace();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunningRace
        /// </summary>
        [Test]
        public void RunningRaceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RunningRace
            //Assert.IsInstanceOfType<RunningRace> (instance, "variable 'instance' is a RunningRace");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RunningRaceType'
        /// </summary>
        [Test]
        public void RunningRaceTypeTest()
        {
            // TODO unit test for the property 'RunningRaceType'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'StartDateLocal'
        /// </summary>
        [Test]
        public void StartDateLocalTest()
        {
            // TODO unit test for the property 'StartDateLocal'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'RouteIds'
        /// </summary>
        [Test]
        public void RouteIdsTest()
        {
            // TODO unit test for the property 'RouteIds'
        }
        /// <summary>
        /// Test the property 'MeasurementPreference'
        /// </summary>
        [Test]
        public void MeasurementPreferenceTest()
        {
            // TODO unit test for the property 'MeasurementPreference'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'WebsiteUrl'
        /// </summary>
        [Test]
        public void WebsiteUrlTest()
        {
            // TODO unit test for the property 'WebsiteUrl'
        }

    }

}
