/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SegmentLeaderboard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SegmentLeaderboardTests
    {
        // TODO uncomment below to declare an instance variable for SegmentLeaderboard
        //private SegmentLeaderboard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SegmentLeaderboard
            //instance = new SegmentLeaderboard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SegmentLeaderboard
        /// </summary>
        [Test]
        public void SegmentLeaderboardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SegmentLeaderboard
            //Assert.IsInstanceOfType<SegmentLeaderboard> (instance, "variable 'instance' is a SegmentLeaderboard");
        }


        /// <summary>
        /// Test the property 'EntryCount'
        /// </summary>
        [Test]
        public void EntryCountTest()
        {
            // TODO unit test for the property 'EntryCount'
        }
        /// <summary>
        /// Test the property 'EffortCount'
        /// </summary>
        [Test]
        public void EffortCountTest()
        {
            // TODO unit test for the property 'EffortCount'
        }
        /// <summary>
        /// Test the property 'KomType'
        /// </summary>
        [Test]
        public void KomTypeTest()
        {
            // TODO unit test for the property 'KomType'
        }
        /// <summary>
        /// Test the property 'Entries'
        /// </summary>
        [Test]
        public void EntriesTest()
        {
            // TODO unit test for the property 'Entries'
        }

    }

}
