/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SmoothVelocityStream
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SmoothVelocityStreamTests
    {
        // TODO uncomment below to declare an instance variable for SmoothVelocityStream
        //private SmoothVelocityStream instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmoothVelocityStream
            //instance = new SmoothVelocityStream();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmoothVelocityStream
        /// </summary>
        [Test]
        public void SmoothVelocityStreamInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SmoothVelocityStream
            //Assert.IsInstanceOfType<SmoothVelocityStream> (instance, "variable 'instance' is a SmoothVelocityStream");
        }


        /// <summary>
        /// Test the property 'OriginalSize'
        /// </summary>
        [Test]
        public void OriginalSizeTest()
        {
            // TODO unit test for the property 'OriginalSize'
        }
        /// <summary>
        /// Test the property 'Resolution'
        /// </summary>
        [Test]
        public void ResolutionTest()
        {
            // TODO unit test for the property 'Resolution'
        }
        /// <summary>
        /// Test the property 'SeriesType'
        /// </summary>
        [Test]
        public void SeriesTypeTest()
        {
            // TODO unit test for the property 'SeriesType'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
