/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Split
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SplitTests
    {
        // TODO uncomment below to declare an instance variable for Split
        //private Split instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Split
            //instance = new Split();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Split
        /// </summary>
        [Test]
        public void SplitInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Split
            //Assert.IsInstanceOfType<Split> (instance, "variable 'instance' is a Split");
        }


        /// <summary>
        /// Test the property 'AverageSpeed'
        /// </summary>
        [Test]
        public void AverageSpeedTest()
        {
            // TODO unit test for the property 'AverageSpeed'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'ElapsedTime'
        /// </summary>
        [Test]
        public void ElapsedTimeTest()
        {
            // TODO unit test for the property 'ElapsedTime'
        }
        /// <summary>
        /// Test the property 'ElevationDifference'
        /// </summary>
        [Test]
        public void ElevationDifferenceTest()
        {
            // TODO unit test for the property 'ElevationDifference'
        }
        /// <summary>
        /// Test the property 'PaceZone'
        /// </summary>
        [Test]
        public void PaceZoneTest()
        {
            // TODO unit test for the property 'PaceZone'
        }
        /// <summary>
        /// Test the property 'MovingTime'
        /// </summary>
        [Test]
        public void MovingTimeTest()
        {
            // TODO unit test for the property 'MovingTime'
        }
        /// <summary>
        /// Test the property '_Split'
        /// </summary>
        [Test]
        public void _SplitTest()
        {
            // TODO unit test for the property '_Split'
        }

    }

}
