/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StreamSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StreamSetTests
    {
        // TODO uncomment below to declare an instance variable for StreamSet
        //private StreamSet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StreamSet
            //instance = new StreamSet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StreamSet
        /// </summary>
        [Test]
        public void StreamSetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StreamSet
            //Assert.IsInstanceOfType<StreamSet> (instance, "variable 'instance' is a StreamSet");
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Latlng'
        /// </summary>
        [Test]
        public void LatlngTest()
        {
            // TODO unit test for the property 'Latlng'
        }
        /// <summary>
        /// Test the property 'Altitude'
        /// </summary>
        [Test]
        public void AltitudeTest()
        {
            // TODO unit test for the property 'Altitude'
        }
        /// <summary>
        /// Test the property 'VelocitySmooth'
        /// </summary>
        [Test]
        public void VelocitySmoothTest()
        {
            // TODO unit test for the property 'VelocitySmooth'
        }
        /// <summary>
        /// Test the property 'Heartrate'
        /// </summary>
        [Test]
        public void HeartrateTest()
        {
            // TODO unit test for the property 'Heartrate'
        }
        /// <summary>
        /// Test the property 'Cadence'
        /// </summary>
        [Test]
        public void CadenceTest()
        {
            // TODO unit test for the property 'Cadence'
        }
        /// <summary>
        /// Test the property 'Watts'
        /// </summary>
        [Test]
        public void WattsTest()
        {
            // TODO unit test for the property 'Watts'
        }
        /// <summary>
        /// Test the property 'Temp'
        /// </summary>
        [Test]
        public void TempTest()
        {
            // TODO unit test for the property 'Temp'
        }
        /// <summary>
        /// Test the property 'Moving'
        /// </summary>
        [Test]
        public void MovingTest()
        {
            // TODO unit test for the property 'Moving'
        }
        /// <summary>
        /// Test the property 'GradeSmooth'
        /// </summary>
        [Test]
        public void GradeSmoothTest()
        {
            // TODO unit test for the property 'GradeSmooth'
        }

    }

}
