/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SummaryGear
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummaryGearTests
    {
        // TODO uncomment below to declare an instance variable for SummaryGear
        //private SummaryGear instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummaryGear
            //instance = new SummaryGear();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummaryGear
        /// </summary>
        [Test]
        public void SummaryGearInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummaryGear
            //Assert.IsInstanceOfType<SummaryGear> (instance, "variable 'instance' is a SummaryGear");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ResourceState'
        /// </summary>
        [Test]
        public void ResourceStateTest()
        {
            // TODO unit test for the property 'ResourceState'
        }
        /// <summary>
        /// Test the property 'Primary'
        /// </summary>
        [Test]
        public void PrimaryTest()
        {
            // TODO unit test for the property 'Primary'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }

    }

}
