/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SummaryClub
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummaryClubTests
    {
        // TODO uncomment below to declare an instance variable for SummaryClub
        //private SummaryClub instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummaryClub
            //instance = new SummaryClub();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummaryClub
        /// </summary>
        [Test]
        public void SummaryClubInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummaryClub
            //Assert.IsInstanceOfType<SummaryClub> (instance, "variable 'instance' is a SummaryClub");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ResourceState'
        /// </summary>
        [Test]
        public void ResourceStateTest()
        {
            // TODO unit test for the property 'ResourceState'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProfileMedium'
        /// </summary>
        [Test]
        public void ProfileMediumTest()
        {
            // TODO unit test for the property 'ProfileMedium'
        }
        /// <summary>
        /// Test the property 'CoverPhoto'
        /// </summary>
        [Test]
        public void CoverPhotoTest()
        {
            // TODO unit test for the property 'CoverPhoto'
        }
        /// <summary>
        /// Test the property 'CoverPhotoSmall'
        /// </summary>
        [Test]
        public void CoverPhotoSmallTest()
        {
            // TODO unit test for the property 'CoverPhotoSmall'
        }
        /// <summary>
        /// Test the property 'SportType'
        /// </summary>
        [Test]
        public void SportTypeTest()
        {
            // TODO unit test for the property 'SportType'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Private'
        /// </summary>
        [Test]
        public void PrivateTest()
        {
            // TODO unit test for the property 'Private'
        }
        /// <summary>
        /// Test the property 'MemberCount'
        /// </summary>
        [Test]
        public void MemberCountTest()
        {
            // TODO unit test for the property 'MemberCount'
        }
        /// <summary>
        /// Test the property 'Featured'
        /// </summary>
        [Test]
        public void FeaturedTest()
        {
            // TODO unit test for the property 'Featured'
        }
        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Test]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
