/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SummarySegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummarySegmentTests
    {
        // TODO uncomment below to declare an instance variable for SummarySegment
        //private SummarySegment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummarySegment
            //instance = new SummarySegment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummarySegment
        /// </summary>
        [Test]
        public void SummarySegmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummarySegment
            //Assert.IsInstanceOfType<SummarySegment> (instance, "variable 'instance' is a SummarySegment");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ActivityType'
        /// </summary>
        [Test]
        public void ActivityTypeTest()
        {
            // TODO unit test for the property 'ActivityType'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'AverageGrade'
        /// </summary>
        [Test]
        public void AverageGradeTest()
        {
            // TODO unit test for the property 'AverageGrade'
        }
        /// <summary>
        /// Test the property 'MaximumGrade'
        /// </summary>
        [Test]
        public void MaximumGradeTest()
        {
            // TODO unit test for the property 'MaximumGrade'
        }
        /// <summary>
        /// Test the property 'ElevationHigh'
        /// </summary>
        [Test]
        public void ElevationHighTest()
        {
            // TODO unit test for the property 'ElevationHigh'
        }
        /// <summary>
        /// Test the property 'ElevationLow'
        /// </summary>
        [Test]
        public void ElevationLowTest()
        {
            // TODO unit test for the property 'ElevationLow'
        }
        /// <summary>
        /// Test the property 'StartLatlng'
        /// </summary>
        [Test]
        public void StartLatlngTest()
        {
            // TODO unit test for the property 'StartLatlng'
        }
        /// <summary>
        /// Test the property 'EndLatlng'
        /// </summary>
        [Test]
        public void EndLatlngTest()
        {
            // TODO unit test for the property 'EndLatlng'
        }
        /// <summary>
        /// Test the property 'ClimbCategory'
        /// </summary>
        [Test]
        public void ClimbCategoryTest()
        {
            // TODO unit test for the property 'ClimbCategory'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Private'
        /// </summary>
        [Test]
        public void PrivateTest()
        {
            // TODO unit test for the property 'Private'
        }
        /// <summary>
        /// Test the property 'AthletePrEffort'
        /// </summary>
        [Test]
        public void AthletePrEffortTest()
        {
            // TODO unit test for the property 'AthletePrEffort'
        }

    }

}
