/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdatableActivity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdatableActivityTests
    {
        // TODO uncomment below to declare an instance variable for UpdatableActivity
        //private UpdatableActivity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdatableActivity
            //instance = new UpdatableActivity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdatableActivity
        /// </summary>
        [Test]
        public void UpdatableActivityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdatableActivity
            //Assert.IsInstanceOfType<UpdatableActivity> (instance, "variable 'instance' is a UpdatableActivity");
        }


        /// <summary>
        /// Test the property 'Commute'
        /// </summary>
        [Test]
        public void CommuteTest()
        {
            // TODO unit test for the property 'Commute'
        }
        /// <summary>
        /// Test the property 'Trainer'
        /// </summary>
        [Test]
        public void TrainerTest()
        {
            // TODO unit test for the property 'Trainer'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'GearId'
        /// </summary>
        [Test]
        public void GearIdTest()
        {
            // TODO unit test for the property 'GearId'
        }

    }

}
