/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ZoneRanges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZoneRangesTests
    {
        // TODO uncomment below to declare an instance variable for ZoneRanges
        //private ZoneRanges instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ZoneRanges
            //instance = new ZoneRanges();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ZoneRanges
        /// </summary>
        [Test]
        public void ZoneRangesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ZoneRanges
            //Assert.IsInstanceOfType<ZoneRanges> (instance, "variable 'instance' is a ZoneRanges");
        }



    }

}
