/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Zones
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ZonesTests
    {
        // TODO uncomment below to declare an instance variable for Zones
        //private Zones instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Zones
            //instance = new Zones();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Zones
        /// </summary>
        [Test]
        public void ZonesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Zones
            //Assert.IsInstanceOfType<Zones> (instance, "variable 'instance' is a Zones");
        }


        /// <summary>
        /// Test the property 'HeartRate'
        /// </summary>
        [Test]
        public void HeartRateTest()
        {
            // TODO unit test for the property 'HeartRate'
        }
        /// <summary>
        /// Test the property 'Power'
        /// </summary>
        [Test]
        public void PowerTest()
        {
            // TODO unit test for the property 'Power'
        }

    }

}
