/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RunningRacesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RunningRacesApiTests
    {
        private RunningRacesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RunningRacesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunningRacesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RunningRacesApi
            //Assert.IsInstanceOfType(typeof(RunningRacesApi), instance, "instance is a RunningRacesApi");
        }

        
        /// <summary>
        /// Test GetRunningRaceById
        /// </summary>
        [Test]
        public void GetRunningRaceByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.GetRunningRaceById(id);
            //Assert.IsInstanceOf<RunningRace> (response, "response is RunningRace");
        }
        
        /// <summary>
        /// Test GetRunningRaces
        /// </summary>
        [Test]
        public void GetRunningRacesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? year = null;
            //var response = instance.GetRunningRaces(year);
            //Assert.IsInstanceOf<List<RunningRace>> (response, "response is List<RunningRace>");
        }
        
    }

}
