/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SegmentEffortsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SegmentEffortsApiTests
    {
        private SegmentEffortsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SegmentEffortsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SegmentEffortsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SegmentEffortsApi
            //Assert.IsInstanceOfType(typeof(SegmentEffortsApi), instance, "instance is a SegmentEffortsApi");
        }

        
        /// <summary>
        /// Test GetEffortsBySegmentId
        /// </summary>
        [Test]
        public void GetEffortsBySegmentIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetEffortsBySegmentId(id, page, perPage);
            //Assert.IsInstanceOf<List<DetailedSegmentEffort>> (response, "response is List<DetailedSegmentEffort>");
        }
        
        /// <summary>
        /// Test GetSegmentEffortById
        /// </summary>
        [Test]
        public void GetSegmentEffortByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetSegmentEffortById(id);
            //Assert.IsInstanceOf<DetailedSegmentEffort> (response, "response is DetailedSegmentEffort");
        }
        
    }

}
