/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SegmentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SegmentsApiTests
    {
        private SegmentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SegmentsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SegmentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SegmentsApi
            //Assert.IsInstanceOfType(typeof(SegmentsApi), instance, "instance is a SegmentsApi");
        }

        
        /// <summary>
        /// Test ExploreSegments
        /// </summary>
        [Test]
        public void ExploreSegmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<float?> bounds = null;
            //string activityType = null;
            //int? minCat = null;
            //int? maxCat = null;
            //var response = instance.ExploreSegments(bounds, activityType, minCat, maxCat);
            //Assert.IsInstanceOf<ExplorerResponse> (response, "response is ExplorerResponse");
        }
        
        /// <summary>
        /// Test GetLeaderboardBySegmentId
        /// </summary>
        [Test]
        public void GetLeaderboardBySegmentIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string gender = null;
            //string ageGroup = null;
            //string weightClass = null;
            //bool? following = null;
            //long? clubId = null;
            //string dateRange = null;
            //int? contextEntries = null;
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetLeaderboardBySegmentId(id, gender, ageGroup, weightClass, following, clubId, dateRange, contextEntries, page, perPage);
            //Assert.IsInstanceOf<SegmentLeaderboard> (response, "response is SegmentLeaderboard");
        }
        
        /// <summary>
        /// Test GetLoggedInAthleteStarredSegments
        /// </summary>
        [Test]
        public void GetLoggedInAthleteStarredSegmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? perPage = null;
            //var response = instance.GetLoggedInAthleteStarredSegments(page, perPage);
            //Assert.IsInstanceOf<List<SummarySegment>> (response, "response is List<SummarySegment>");
        }
        
        /// <summary>
        /// Test GetSegmentById
        /// </summary>
        [Test]
        public void GetSegmentByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetSegmentById(id);
            //Assert.IsInstanceOf<DetailedSegment> (response, "response is DetailedSegment");
        }
        
        /// <summary>
        /// Test StarSegment
        /// </summary>
        [Test]
        public void StarSegmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //bool? starred = null;
            //var response = instance.StarSegment(id, starred);
            //Assert.IsInstanceOf<DetailedSegment> (response, "response is DetailedSegment");
        }
        
    }

}
