/* 
 * Strava API v3
 *
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StreamsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StreamsApiTests
    {
        private StreamsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StreamsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StreamsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' StreamsApi
            //Assert.IsInstanceOfType(typeof(StreamsApi), instance, "instance is a StreamsApi");
        }

        
        /// <summary>
        /// Test GetActivityStreams
        /// </summary>
        [Test]
        public void GetActivityStreamsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //List<string> keys = null;
            //bool? keyByType = null;
            //var response = instance.GetActivityStreams(id, keys, keyByType);
            //Assert.IsInstanceOf<StreamSet> (response, "response is StreamSet");
        }
        
        /// <summary>
        /// Test GetRouteStreams
        /// </summary>
        [Test]
        public void GetRouteStreamsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetRouteStreams(id);
            //Assert.IsInstanceOf<StreamSet> (response, "response is StreamSet");
        }
        
        /// <summary>
        /// Test GetSegmentEffortStreams
        /// </summary>
        [Test]
        public void GetSegmentEffortStreamsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //List<string> keys = null;
            //bool? keyByType = null;
            //var response = instance.GetSegmentEffortStreams(id, keys, keyByType);
            //Assert.IsInstanceOf<StreamSet> (response, "response is StreamSet");
        }
        
        /// <summary>
        /// Test GetSegmentStreams
        /// </summary>
        [Test]
        public void GetSegmentStreamsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //List<string> keys = null;
            //bool? keyByType = null;
            //var response = instance.GetSegmentStreams(id, keys, keyByType);
            //Assert.IsInstanceOf<StreamSet> (response, "response is StreamSet");
        }
        
    }

}
